[package]
name = "ballad-search"
version = "0.1.0"
edition = "2024"

[dependencies]
xdg = { workspace = true }
serde = { workspace = true }
toml = { workspace = true }
url = { version = "2.5.4", features = ["serde"] }
uuid = { version = "1.11.0", features = ["serde", "v4"] }
