[package]
name = "ballad-config"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { workspace = true }
toml = { workspace = true }
xdg = { workspace = true }
gtk = { workspace = true, optional = true }

[features]
gtk = ["dep:gtk"]