[package]
name = "ballad-config"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.216", features = ["derive"] }
toml = "0.8.19"
xdg = { workspace = true }
gtk = { workspace = true, optional = true }

[features]
gtk = ["dep:gtk"]