[package]
name = "ballad-services"
version = "0.1.0"
edition = "2024"

[dependencies]
ballad-config = { workspace = true, features = ["gtk"]}
ballad-macro = { workspace = true }

gtk = { workspace = true }
pulsectl-rs = "0.3.2"
libpulse-binding = "2.28.2"
libc = "0.2.169"
zbus = { workspace = true }

smol = { workspace = true }
futures = { version = "0.3.31", default-features = false, features = ["std", "async-await"] }

serde_json = "1.0.135"
niri-ipc = "25.8.0"
