[package]
name = "ballad-services"
version = "0.1.0"
edition = "2024"

[dependencies]
gtk = { workspace = true }
ballad-config = { workspace = true, features = ["gtk"]}
alsa = { git = "https://github.com/diwic/alsa-rs", version = "0.9.1" }
smol = { workspace = true }
zbus = { workspace = true }
futures = { version = "0.3.31", default-features = false, features = ["std", "async-await"] }
