[package]
name = "ballad-services"
version = "0.1.0"
edition = "2024"

[dependencies]
gtk = { version = "0.9.5", package = "gtk4", features = ["v4_16"] }
ballad-config = { path = "../ballad-config", features = ["gtk"]}