[package]
name = "ballad-shell"
version = "0.1.0"
edition = "2024"

[dependencies]
ballad-services = { workspace = true }
ballad-config = { workspace = true }
ballad-search = { workspace = true }

snafu =  { workspace = true }
smol = { workspace = true }
zbus = { workspace = true }
gtk = { workspace = true }
gtk4-layer-shell = { workspace = true }

typed-builder = { workspace = true } 
grass = { version = "0.13.4", default-features = false }
chrono = "0.4.39"
clap = { version = "4.5.24", features = ["derive"] }
smol-macros = "0.1.1"
libc = "0.2.169"

[build-dependencies]
glib-build-tools = "0.20.0"
